# Generated by Django 5.2.18 on 2026-10-07 12:55

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('google_place_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('google_maps_url', models.TextField(blank=True, null=True)),
                ('google_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('google_review_count', models.IntegerField(blank=True, null=True)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('first_discovered_at', models.DateTimeField(blank=True, null=True)),
                ('last_discovered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'db_table': 'businesses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('role_type', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=320, null=True)),
                ('email_source', models.CharField(blank=True, help_text='website, search, inferred or pattern are replaced when discovery reruns; any other value (e.g. manual) is kept.', max_length=32, null=True)),
                ('email_status', models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('deliverable', 'Deliverable'), ('undeliverable', 'Undeliverable'), ('risky', 'Risky'), ('unknown', 'Unknown')], default='unverified', max_length=32, null=True)),
                ('email_checked_at', models.DateTimeField(blank=True, null=True)),
                ('email_check_details', models.JSONField(blank=True, null=True)),
                ('candidate_emails', models.JSONField(blank=True, default=list)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('discovery_reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='pipeline.business')),
            ],
            options={
                'db_table': 'business_contacts',
                'ordering': ['business_id', '-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('source_business_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='pipeline.business')),
            ],
            options={
                'db_table': 'business_sources',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessWebsiteProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('pages_scraped', models.IntegerField(default=0)),
                ('scraped_urls', models.JSONField(blank=True, default=list)),
                ('scraped_pages', models.JSONField(blank=True, default=list)),
                ('discovered_links', models.JSONField(blank=True, default=list)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('qualification_score', models.IntegerField(blank=True, null=True)),
                ('qualification_reasons', models.JSONField(blank=True, default=list)),
                ('agent_reasoning', models.TextField(blank=True, null=True)),
                ('contact_discovery_status', models.CharField(blank=True, choices=[('completed', 'Contacts found'), ('no_contacts', 'No contacts found')], db_index=True, help_text='Set by contact discovery (Module 3). Clear it to let discovery run again.', max_length=32, null=True)),
                ('contact_discovery_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_profile', to='pipeline.business')),
            ],
            options={
                'db_table': 'business_website_profiles',
                'ordering': ['-qualification_score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_country', models.CharField(blank=True, help_text='One country, e.g. Pakistan.', max_length=100, null=True)),
                ('target_locations', models.JSONField(blank=True, default=list, help_text='List of places, e.g. ["Lahore", "Karachi"].', null=True)),
                ('search_terms', models.JSONField(blank=True, default=list, help_text='List of searches, e.g. ["dental clinic"].', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discovery_campaigns',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'completed', 'failed'])), name='ck_discovery_campaigns_status')],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='discovery_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='pipeline.discoverycampaign'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_step', models.IntegerField(default=1)),
                ('recipient', models.CharField(max_length=320)),
                ('subject', models.TextField()),
                ('body_text', models.TextField()),
                ('body_html', models.TextField()),
                ('tracking_token', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sending', 'Sending'), ('sent', 'Sent'), ('opened', 'Opened'), ('failed', 'Failed')], db_index=True, default='in_review', max_length=32)),
                ('generation_provider', models.CharField(blank=True, max_length=32, null=True)),
                ('generation_model', models.CharField(blank=True, max_length=128, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_from', models.CharField(blank=True, max_length=320, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('send_error', models.TextField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='pipeline.business')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='pipeline.businesscontact')),
            ],
            options={
                'db_table': 'emails',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmailOpenEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_events', to='pipeline.email')),
            ],
            options={
                'db_table': 'email_open_events',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=320)),
                ('email_status', models.CharField(blank=True, choices=[('deliverable', 'Deliverable'), ('undeliverable', 'Undeliverable'), ('risky', 'Risky'), ('unknown', 'Unknown')], db_index=True, max_length=32, null=True)),
                ('email_verification_provider', models.CharField(blank=True, max_length=64, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('qualification_score', models.IntegerField(blank=True, null=True)),
                ('outreach_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('needs_review', 'Needs review'), ('rejected', 'Rejected'), ('contacted', 'Contacted')], db_index=True, default='pending', max_length=32)),
                ('outreach_priority', models.CharField(blank=True, max_length=16, null=True)),
                ('outreach_facts', models.JSONField(blank=True, default=list)),
                ('research_summary', models.TextField(blank=True, null=True)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='pipeline.business')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='pipeline.businesscontact')),
            ],
            options={
                'db_table': 'prospects',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='email',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='pipeline.prospect'),
        ),
        migrations.AddConstraint(
            model_name='businesscontact',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='ck_business_contacts_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='prospect',
            constraint=models.UniqueConstraint(fields=('contact', 'email'), name='uq_prospects_contact_email'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('prospect', 'sequence_step'), name='uq_emails_prospect_step'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_review', 'approved', 'rejected', 'sending', 'sent', 'opened', 'failed'])), name='ck_emails_status'),
        ),
    ]
