# Generated by Django 5.2.18 on 2026-10-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_pipeline_runs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscontact',
            options={'ordering': ['business_id', '-is_primary', 'id'], 'verbose_name': 'contact'},
        ),
        migrations.AlterModelOptions(
            name='businesssource',
            options={'ordering': ['id'], 'verbose_name': 'Google Maps listing'},
        ),
        migrations.AlterModelOptions(
            name='businesswebsiteprofile',
            options={'ordering': ['-qualification_score', 'id'], 'verbose_name': 'website research', 'verbose_name_plural': 'website research'},
        ),
        migrations.AlterModelOptions(
            name='discoverycampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'campaign'},
        ),
        migrations.AlterModelOptions(
            name='emailopenevent',
            options={'ordering': ['-opened_at'], 'verbose_name': 'email open'},
        ),
    ]
