# Generated by Django 5.2.18 on 2026-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_friendly_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='verdict',
            field=models.CharField(blank=True, choices=[('deliverable', 'Deliverable'), ('catch_all', 'Catch-all domain'), ('full_inbox', 'Inbox full'), ('disposable', 'Disposable address'), ('risky', 'Risky'), ('mailbox_not_found', 'Mailbox not found'), ('disabled', 'Mailbox disabled'), ('no_mail_server', 'Domain has no mail server'), ('invalid_syntax', 'Invalid address'), ('smtp_unreachable', 'Mail server unreachable'), ('blocked', 'Mail server refused the check'), ('temporary_failure', 'Temporary failure (greylisting)'), ('check_failed', 'Check failed'), ('unknown', 'Unknown')], db_index=True, help_text='Why verification gave this status, e.g. catch_all or mailbox_not_found.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='verification_details',
            field=models.JSONField(blank=True, help_text="Reacher's findings for this address.", null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='verification_note',
            field=models.TextField(blank=True, null=True),
        ),
        # Prospects stored before verdicts existed were all deliverable.
    migrations.RunSQL(
        "UPDATE prospects SET verdict = 'deliverable' WHERE verdict IS NULL AND email_status = 'deliverable'",
        reverse_sql=migrations.RunSQL.noop,
    ),
]
