# Generated by Django 5.2.18 on 2026-10-09 08:34

import django.db.models.deletion
from django.db import migrations, models


def seed_default_prompts(apps, schema_editor):
    """Save the built-in Axioware prompt as the first campaign and email prompts, used by the oldest campaign."""
    from pipeline.services.generation import DEFAULT_CAMPAIGN_PROMPT, DEFAULT_EMAIL_PROMPT

    CampaignPrompt = apps.get_model("pipeline", "CampaignPrompt")
    EmailPrompt = apps.get_model("pipeline", "EmailPrompt")
    DiscoveryCampaign = apps.get_model("pipeline", "DiscoveryCampaign")
    campaign_prompt, _ = CampaignPrompt.objects.get_or_create(
        name="Axioware - dental clinics", defaults={"prompt": DEFAULT_CAMPAIGN_PROMPT})
    EmailPrompt.objects.get_or_create(campaign_prompt=campaign_prompt, name="First-touch email",
                                      defaults={"prompt": DEFAULT_EMAIL_PROMPT, "is_default": True})
    campaign = DiscoveryCampaign.objects.filter(campaign_prompt__isnull=True).order_by("created_at").first()
    if campaign is not None and not DiscoveryCampaign.objects.filter(campaign_prompt=campaign_prompt).exists():
        campaign.campaign_prompt = campaign_prompt
        campaign.save(update_fields=["campaign_prompt"])


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_prospect_verdicts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('prompt', models.TextField(help_text='Who we are, what we offer, the rules every email must follow and the output format. The chosen email prompt is added after it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaign_prompts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='discoverycampaign',
            name='campaign_prompt',
            field=models.OneToOneField(blank=True, help_text="Instructions used to write this campaign's emails. Each prompt belongs to one campaign.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign', to='pipeline.campaignprompt'),
        ),
        migrations.CreateModel(
            name='EmailPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField(help_text='How to write this email: structure, call to action, length and style.')),
                ('is_default', models.BooleanField(default=False, help_text='Used when no email prompt is chosen.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_prompts', to='pipeline.campaignprompt')),
            ],
            options={
                'db_table': 'email_prompts',
                'ordering': ['campaign_prompt__name', '-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='email',
            name='email_prompt',
            field=models.ForeignKey(blank=True, help_text='The email prompt this email was written with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='pipeline.emailprompt'),
        ),
        migrations.AddConstraint(
            model_name='emailprompt',
            constraint=models.UniqueConstraint(fields=('campaign_prompt', 'name'), name='uq_email_prompts_name'),
        ),
        migrations.AddConstraint(
            model_name='emailprompt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('campaign_prompt',), name='uq_email_prompts_one_default'),
        ),
        migrations.RunPython(seed_default_prompts, migrations.RunPython.noop),
    ]
